port: 8080
backends:
  - url: "http://localhost:8001"
    weight: 100
  - url: "http://localhost:8002"
    weight: 200
health_tick: 12
rate_limiting:
  default_capacity: 10  # Макс. количество запросов
  default_rate: 1       # 10 запросов в секунду